### ISSUE TITLE
Support of h2

### ISSUE THREAD

**Issue by dinosaure** [roburio/http-lwt-client#1]
The support of `h2` should be easy when the _runtime_ is pretty the same as `http/af`. `paf` uses the same loop implementation for both and the runtime is defined by a compon signature.

**Comment by anmonteiro** [comment]
It's different for the client. h2 supports multiple requests on the same connection, whereas http/af doesn't. My fork of http/af supports persistent client connections and pipelining on the client, though.

**Comment by hannesm** [comment]
Hmm, that is an interesting feature request. Eventually. I have not really read up on HTTP2 at all, neither do I know how widely it is deployed.

But indeed, I just looked up h2 (thanks @anmonteiro), and the base library has a pretty smooth dependency cone that I'd be fine with to depend...

@anmonteiro Indeed your piaf & http/af fork support more things -- this library here has a slightly different target.

**Comment by hannesm** [comment]
thanks, #2 is merged now
