### ISSUE TITLE
http-lwt-client does not make use of lwt when downloading something

### ISSUE THREAD

**Issue by kit-ty-kate** [roburio/http-lwt-client#12]
The following code:
```
open Lwt.Infix

let main () =
  let dl =
    Http_lwt_client.one_request
      ~meth:`GET
      "https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/aarch64/alpine-netboot-3.16.2-aarch64.tar.gz"
    >>= fun _ ->
    Lwt_io.printf "FINISHED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n%!"
  in
  let loop =
    let rec loop prev_time =
      let current_time = Unix.gettimeofday () in
      Lwt_io.printf "loop took %f seconds\n%!" (current_time -. prev_time) >>= fun () ->
      loop current_time
    in
    loop (Unix.gettimeofday ())
  in
  Lwt.choose [dl; loop]

let () = Lwt_main.run (main ())
```
Will give the following output:
```
$ ./a.out
[...]
loop took 0.000001 seconds
loop took 0.000002 seconds
loop took 0.000002 seconds
loop took 0.000001 seconds
loop took 0.000002 seconds
loop took 0.000002 seconds
loop took 0.000002 seconds
FINISHED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
loop took 60.805441 seconds
loop took 0.000018 seconds
loop took 0.000004 seconds
loop took 0.000002 seconds
loop took 0.000003 seconds
loop took 0.000001 seconds
loop took 0.000002 seconds
loop took 0.000002 seconds
loop took 0.000002 seconds
[...]
```
As you can see the process stopped doing anything concurrent for a whole 60 secondes while it was downloading the tarball.
Looking at the code, it looks like you are using the non asynchronous versions of `Httpaf.Body`.

**Comment by kit-ty-kate** [comment]
While you are looking at this part of the code, I would also be very interested in having a version of `one_request` that returns a `Lwt_stream.t` (or something like that), instead of one large string for the body.

**Comment by hannesm** [comment]
Thanks for your report, and @dinosaure fixing it in #13 (which I merged, and released)

> I would also be very interested in having a version of `one_request` that returns `a Lwt_stream.t` (or something like that), instead of one large string for the body.

Could you please open a separate issue, so we keep track of that feature wish? Is your use-case the response body or the request body, which should be a `Lwt_stream.t`?

**Comment by kit-ty-kate** [comment]
@hannesm I opened a PR here: https://github.com/roburio/http-lwt-client/pull/14, streams wouldn't really fit the library and the fold format is a lot more general anyway ^^
