### ISSUE TITLE
File descriptor leak when using h2

### ISSUE THREAD

**Issue by reynir** [roburio/http-lwt-client#22]
I have an application that queries on a regular interval an opam repository. Two instances run, one querying opam.ocaml.org and the other opam.robur.coop. The former is leaking file descriptors while the latter doesn't.

I need to verify, but running `curl -v https://opam.{ocaml.org,robur.coop}` curl at least uses h2 for opam.ocaml.org and http/1.1 for opam.robur.coop, and I suspect it is the same for http-lwt-client.

**Comment by reynir** [comment]
Looking at the code I don't see where the file descriptor is closed. So it may just be opam.robur.coop being more eager to close client connections. I will look more into it tomorrow.

**Comment by reynir** [comment]
The socket is closed in `Http_lwt_unix` once the reader and writer loops signal they've exited.
https://github.com/robur-coop/http-lwt-client/blob/b23065a2e781b38c43628e3cf881cc058b0fb185/src/http_lwt_unix.ml#L225-L236

I wrote a crude test (that depends on brittle assumptions): https://github.com/reynir/http-lwt-client/tree/test-fd-leak

What I discovered is that 
- this seems to only occur with h2, and not https/1.1 from testing about half a dozen websites,
- the read loop and write loop never signal they've exited for h2 (but they do for http/1.1)

**Comment by hannesm** [comment]
In http-mirage-client, what we do is:

```OCaml
let single_request
    ~ctx ~alpn_protocol ?config cfg ~meth ~headers ?body uri f f_init =
  ...
  Mimic.resolve ctx >>? fun flow ->
  (match .. with
   | `HTTP2 -> single_h2_request
   | _ -> single_http_1_1_request) >>= fun r ->
  Mimic.close flow >>= fun () ->
```

And so, the last line does an explicit close of the flow.

With the same reasoning in mind, in http-lwt-client, we do a `connect ... >>= fun fd -> <request>`, and could after the request explicitly close the `fd`. In my brain, the best resource management is "the code allocating a resource (file descriptor) is responsible for clearing it up". Certainly there is the danger of double closes (also see https://discuss.ocaml.org/t/detect-use-after-close-of-unix-file-descriptors as related discussion). There's not much we can do to avoid these double close (apart from relying on http/af and h2 to properly close fd's (or our Http_lwt_unix module) -- but it looks like this is not the case :/).
